# Generated by Django 5.1.3 on 2024-12-02 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=models.TextField(default='Contenido predeterminado'),
        ),
    ]
